import { Theme } from './types';

export const GRID_SIZE = 4;

export const TRANSLATIONS = {
  en: {
    score: 'Score',
    best: 'Best',
    newGame: 'New Game',
    archive: 'Archive',
    gameOver: 'Game Over',
    youWin: 'You Win!',
    tryAgain: 'Try Again',
    keepGoing: 'Keep Going',
    howToPlay: 'Use arrow keys or swipe.',
    howToPlay2: 'Reach 2048 to win!',
    howToPlayMobile: 'Swipe to move. Reach 2048.',
    saveModalTitle: 'Game Archive',
    quickSave: 'Quick Save (Device)',
    save: 'Save',
    load: 'Load',
    currentSaveCode: 'Current Save Code',
    copy: 'Copy',
    copied: 'Copied!',
    loadSaveCode: 'Load Save Code',
    pastePlaceholder: 'Paste save code here...',
    loadGameCode: 'Load Game Code',
    invalidCode: 'Invalid save code.',
    noLocalSave: 'No local save found.',
    savedToLocal: 'Game Saved to Local Storage!',
  },
  zh: {
    score: '得分',
    best: '最高分',
    newGame: '新游戏',
    archive: '存档',
    gameOver: '游戏结束',
    youWin: '你赢了！',
    tryAgain: '再试一次',
    keepGoing: '继续游戏',
    howToPlay: '使用方向键或滑动移动。',
    howToPlay2: '合成2048获胜！',
    howToPlayMobile: '滑动移动方块。合成2048。',
    saveModalTitle: '游戏存档',
    quickSave: '快速存档 (本地)',
    save: '保存',
    load: '读取',
    currentSaveCode: '当前存档码',
    copy: '复制',
    copied: '已复制',
    loadSaveCode: '读取存档码',
    pastePlaceholder: '在此粘贴存档码...',
    loadGameCode: '读取存档',
    invalidCode: '无效的存档码',
    noLocalSave: '未找到本地存档',
    savedToLocal: '游戏已保存到本地！',
  }
};

export const THEMES: Record<string, Theme> = {
  classic: {
    name: 'Classic',
    appBg: 'bg-[#faf8ef]',
    gridBg: 'bg-[#bbada0]',
    emptyCellBg: 'bg-[#cdc1b4]',
    textColor: 'text-[#776e65]',
    scoreBg: 'bg-[#bbada0]',
    scoreText: 'text-white',
    buttonBg: 'bg-[#8f7a66]',
    buttonText: 'text-white',
    tileColors: {
      2: 'bg-[#eee4da]',
      4: 'bg-[#ede0c8]',
      8: 'bg-[#f2b179]',
      16: 'bg-[#f59563]',
      32: 'bg-[#f67c5f]',
      64: 'bg-[#f65e3b]',
      128: 'bg-[#edcf72]',
      256: 'bg-[#edcc61]',
      512: 'bg-[#edc850]',
      1024: 'bg-[#edc53f]',
      2048: 'bg-[#edc22e]',
    },
    tileTextColors: {
      2: 'text-[#776e65]',
      4: 'text-[#776e65]',
    },
  },
  midnight: {
    name: 'Midnight',
    appBg: 'bg-slate-900',
    gridBg: 'bg-slate-800',
    emptyCellBg: 'bg-slate-700',
    textColor: 'text-slate-100',
    scoreBg: 'bg-slate-700',
    scoreText: 'text-blue-300',
    buttonBg: 'bg-indigo-600',
    buttonText: 'text-white',
    tileColors: {
      2: 'bg-indigo-400',
      4: 'bg-indigo-500',
      8: 'bg-violet-500',
      16: 'bg-violet-600',
      32: 'bg-purple-600',
      64: 'bg-purple-700',
      128: 'bg-fuchsia-600',
      256: 'bg-fuchsia-700',
      512: 'bg-pink-600',
      1024: 'bg-pink-700',
      2048: 'bg-rose-600',
    },
    tileTextColors: {},
  },
  bubblegum: {
    name: 'Bubblegum',
    appBg: 'bg-pink-50',
    gridBg: 'bg-pink-200',
    emptyCellBg: 'bg-pink-100',
    textColor: 'text-pink-900',
    scoreBg: 'bg-pink-300',
    scoreText: 'text-pink-900',
    buttonBg: 'bg-pink-500',
    buttonText: 'text-white',
    tileColors: {
      2: 'bg-pink-300',
      4: 'bg-pink-400',
      8: 'bg-rose-300',
      16: 'bg-rose-400',
      32: 'bg-orange-300',
      64: 'bg-orange-400',
      128: 'bg-yellow-300',
      256: 'bg-yellow-400',
      512: 'bg-lime-300',
      1024: 'bg-lime-400',
      2048: 'bg-teal-400',
    },
    tileTextColors: {
      2: 'text-pink-900',
      4: 'text-pink-900',
      8: 'text-pink-900',
      16: 'text-white',
    },
  },
  forest: {
    name: 'Forest',
    appBg: 'bg-stone-100',
    gridBg: 'bg-stone-300',
    emptyCellBg: 'bg-stone-200',
    textColor: 'text-stone-800',
    scoreBg: 'bg-stone-400',
    scoreText: 'text-white',
    buttonBg: 'bg-emerald-600',
    buttonText: 'text-white',
    tileColors: {
      2: 'bg-emerald-200',
      4: 'bg-emerald-300',
      8: 'bg-teal-400',
      16: 'bg-teal-500',
      32: 'bg-cyan-500',
      64: 'bg-cyan-600',
      128: 'bg-sky-500',
      256: 'bg-sky-600',
      512: 'bg-blue-500',
      1024: 'bg-blue-600',
      2048: 'bg-indigo-600',
    },
    tileTextColors: {
      2: 'text-stone-800',
      4: 'text-stone-800',
    },
  }
};